"""empty message

Revision ID: c0c16a9a4a3a
Revises: 03e762ff1f0d
Create Date: 2024-02-01 15:43:39.914681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import uuid


# revision identifiers, used by Alembic.
revision: str = 'c0c16a9a4a3a'
down_revision: Union[str, None] = '03e762ff1f0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("INSERT INTO type_of_mark (id, type_of_mark) VALUES (gen_random_uuid(), 'LABMARK'), (gen_random_uuid(), 'COURSEWORK')")
    op.execute("INSERT INTO attendance (id, type) VALUES (gen_random_uuid(), 'PRESENT'), (gen_random_uuid(), 'ABSENT')")
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
