"""empty message

Revision ID: cca605c1466f
Revises: d7c3429aa965
Create Date: 2024-01-19 00:36:08.949147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cca605c1466f'
down_revision: Union[str, None] = 'd7c3429aa965'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('title', sa.String(length=50), nullable=False),
                    sa.Column('text', sa.String(length=500), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=False),
                    sa.Column('author_id', sa.Uuid()),
                    sa.Column('module_id', sa.Uuid()),
                    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
                    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("posts")
    # ### end Alembic commands ###
