"""empty message

Revision ID: d7c3429aa965
Revises: c9f8c618a650
Create Date: 2024-01-16 00:20:16.358146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7c3429aa965'
down_revision: Union[str, None] = 'c9f8c618a650'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('images',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.Column('image_date', sa.LargeBinary, nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ###
